# Generated by Django 4.0.3 on 2022-03-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_totalcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalCart',
        ),
    ]
