# Generated by Django 4.0.3 on 2022-03-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='default.jpg', upload_to='product_images'),
        ),
    ]
